version: '3.8'
 
services:
  mongo:
    image: mongo:6.0
    container_name: hrapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: .
    container_name: hrapp-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/hrapp
    depends_on:
      - mongo
 
volumes:
  mongo-data: